train_data:
  train_audio_sample_rate: 48000
  audio_samples_per_llm_token: 7680
  sources:
    - name: ljspeech_basic
      weight: 1.0
      pipeline: basic
      adapter:
        class_name: JsonlManifestSourceAdapter
        params:
          manifest_path: downloaded_data/ljspeech_48khz_manifest_train.jsonl
          shuffle: true
    - name: ljspeech_interleave
      weight: 1.0
      pipeline: interleave
      adapter:
        class_name: JsonlManifestSourceAdapter
        params:
          manifest_path: downloaded_data/ljspeech_48khz_manifest_train.jsonl
          shuffle: true
    # append other sources here if need
  num_tokens_per_epoch: 2000000
  num_workers: 20
  pin_memory: true
  max_audio_seconds_in_batch: 30.0
  max_text_tokens_in_batch: 2048
  max_samples_per_batch: null
  bucketing_pool_size: 100
val_data:
  train_audio_sample_rate: 48000
  audio_samples_per_llm_token: 7680
  sources:
    - name: ljspeech_valid_basic
      weight: 1.0
      adapter:
        class_name: JsonlManifestSourceAdapter
        params:
          manifest_path: downloaded_data/ljspeech_48khz_manifest_valid.jsonl
          shuffle: false
      pipeline: basic
    - name: ljspeech_valid_interleave
      weight: 1.0
      pipeline: interleave
      adapter:
        class_name: JsonlManifestSourceAdapter
        params:
          manifest_path: downloaded_data/ljspeech_48khz_manifest_valid.jsonl
          shuffle: false
      pipeline: interleave
    # append other sources here if need
  num_workers: 4
  pin_memory: true
  max_audio_seconds_in_batch: 30.0
  max_text_tokens_in_batch: 2048
  max_samples_per_batch: null
  bucketing_pool_size: 64
train:
  pretrained_model_path: pretrained_models/pretrain_cpt_decay/latest/model/
  output_dir: debug_train/run_003
  seed: 42
  learning_rate: 1.0e-05
  weight_decay: 0.01
  warmup_steps: 50
  max_train_steps: 500
  gradient_accumulation_steps: 2
  grad_clip_norm: 1
  save_interval: 500
  max_checkpoints_to_keep: 40
  log_interval: 10
  eval_interval: 100
  max_eval_batches: null
  run_eval_on_start: false
loss:
  ce_weight: 1.0
  fm_weight: 1.0
  eos_weight: 1.0
